language: node_js
node_js:
  - node
cache:
  directories:
  - node_modules
dist: trusty
sudo: false
install: 
  - npm ci
before_deploy:
  - npm run build
  - rm -rf node_modules
deploy:
  skip_cleanup: true 
  provider: heroku
  app: swapi-strikes-back
  api_key:
    secure: MLdELznk4BQmcHOnmuW+zNQkC7EeHDphN7b5mv9gudbeF8RRSJPkbY8chaYcLkJfR2cKZLylpoe1ubzAa3Je4Vs66jAlxjJ8UG7CG0FIRq/tUKUbZWozrYJLjewB6/UA39PoVytjL4pXbeVot8Euf8wYhFA4hyJaDcyZfgtyzuYLjeKskGD06+JPsGFkt941NkRt/d01L5txx6tL4YnCqKWSIZ0gvU+WSgV8Xpw5kK+AWM10PwG5A8IL6/njM9JWqynkd0x9UVFVqKaGkm2dHH1YBBl5KpK7OeMev4j12ll3lOam/VexUWDHBDZHQKtMPFALvn+wyRYW+bBFYmIStYiTCVUF6CRQeLX5LgQIrhNfaYoMo5brITQcyeN0OETCzYCXV81hcOgHKvAbzrom/GaaJkavha+H2uH67sul8CLRsmCe7XylDO/w2MjEmrmhHWYsdh/fyxgDY5w2pSN2mM3z0eckYxqTzJSLxLeWKfNcHIlOjsxC/EcQhSoGYh8SOpOEQAgOJF81VnAJN3aFTt26IcHCW1nxSANIuUnWmOTj71GTdZFQq5TXTGy9PjuZkcCW8irC2M0oTQAyyuaT8XX9BNO4bYFg6qn8EEKNpbsitMHzNxWB+A/dYj8fKwSbSJllD3ZgUw2EwhA+Y2Ze/X839Z/1oWIAYk3/XJ77ywQ=