language: node_js
node_js:
  - node
cache:
  directories:
  - node_modules
dist: trusty
sudo: false
install: 
  - npm ci
before_deploy:
  - npm run build
  - rm -rf node_modules
deploy:
  skip_cleanup: true 
  provider: heroku
  app: swapi-strikes-back
  api_key:
    secure: imfe4AVyI40W2LfnkNW80N1ANPyuxjSJED3sdMLpnIYaX0DPiEApu/2QRuA9wHReRnfUGcizH3raFyesugVoeNip+/xOLDPanWyjGD70I0CeJN8DfiEmYnLbUP+fAAgDPA/3n6DopVAMyg+vgOrVPAabmMiVAUre0VQnblg0g7HG/nh+uY39+gISKUXKu8vH9v1Jxe763cy/LIWrKrFlscZU4vbhXwkUn7qXvjR+j6woxSXtRc1tFittd/De4W05QcMPEyxYNYzT1N8eVacqjQ7lWd7tBRsDIsBmuq1fhYt/7heLLiAk2Pj65xNqV9QfRcKZDrQ+huoHISMvvIEqBJdghUVVwZgiRmEl6gAuouZDOFyYvNYOqQ+j2/uJ/rLCtSbg+2BqfF/jXOsmeM/Us/iMwUzeI0eDmdeLIYnb4WZ4QE13OmXGFarPGVSTJARf92CPFh5z6WJcV3aLOb11hheEv7dTf8ZVefLKh5g4ZKuTdH1eKJ5x3kW5C/s6pbU1/OGbBrZQZKrG7GWVPBcvx2McokveY0O+WT+xRakb2OsZc7OzBElw0wBnga5l9dNrL8s6N5J2RXZ4qw0mmK8LhOnPO6+bHlE06brD8VsoCw+HXrGmr1z7i0/om7HDXWVcY6GrG+OKzkHLD/SBnmNlcsf57dYO2cmU0cmmDsUEQzM=