language: node_js
node_js:
  - node
cache:
  directories:
  - node_modules
dist: trusty
sudo: false
install: 
  - npm ci
before_deploy:
  - npm run build
  - rm -rf node_modules
deploy:
  skip_cleanup: true 
  provider: heroku
  app: swapi-strikes-back
  api_key:
    secure: "bq9sQVajtW99eekvn0GuDzh8b3+C62GqWlv0jYOq72Ip2ziohb5dauQNyhqTMui+y3uC8LaV2GRTerxquaqD/ThHPujJ5oCHf43G/L0pUerDm3eDcwedWezjmQhQtXYZEpcnpX2hSWccf7+QVxA/lOX5rASzWNKCqrBznJA/aJkc9+1d+LqeRBXgCWel9brJ7Y5YcLePJfeqm0jXPakhjU0ME+DfIsXwfTnVQIz4B0ASKnf4ummfZFLCDIAGvJf4Haoj6Qred0EP/p+qmp14Ndvbovv1ESISrRRBgeZVcsruJyuvY5OTmXWipwo7Z9f2BOrM7BVTpPPEE4n0jW+VqfI3pzs29d9GLm3Ae810AE6I+7FplA0lhdeGpKk7UAnnpsKMy084Q5iaGlRHZm4Oz8ELlBCj2ycBdusfzyr6eAofPiMwGAWQdUHF4tnklj2wM26SXTnd4b1TI3j0+atNV8Sh3lGHlU8/SjlLWPuJQCVz0GHJwA7uo8lJykc2gENKkpy7i7PHbIu6iVMGCaD0oBo90cozDTvDNRhOC9U+JkKs6XWLiLVJrG+VIvJOv7nYi56ZgsLQr+e1qDMLGO0uaSt7DxgmVroxgib7RmnEzU7NnVv0Fjmd6/BWSurn+xRm2AhyAHuEkvcCyZm65ireg2BN3nYda5vey8KEdpM6I7Q="