language: node_js
node_js:
  - node
cache:
  directories:
  - node_modules
dist: trusty
sudo: false
install: 
  - npm ci
before_deploy:
  - npm run build
  - rm -rf node_modules
deploy:
  skip_cleanup: true 
  provider: heroku
  app: star-warsapi
  api_key:
    secure: "cfHVhuo2/LfS9/zSVIPSG2KYqMVW9npuJfHNWnn/K9s41Zfl3OIr2YeQooX16ux5AMzBVkZQdgBA+DczzUr8WOHxEA7hiqcBdVOGrD/0aJGT0TLzrn3a6ygL80BXUd9XWuP2HRP2p0kzqajJ2V3xD4zQILmWpdHoKjFCqRN1lrlKoipCo5d/jiggmU13lRjW+RXb8prTSZMGZljffuIRSaAyMgvbZJs9Lx2fIGsXoGlBVQ6iJPd0L6TaGEU5lfzQH2Z7Bzm8xCyE97JFseFzZF6qVhzL/wURMTVfsmMN1y2UXLNkd0HSWc0TLknu0peAWfeSEcwpG+zdEZA84DlY814VDFo2DysLgh39lek+I+WhHEtigRcwtVOVs1iZI4b5B964Ix2bFX65bp9ohpskdbN18V10A2lRi1SZNNPos6p6WZUIlJnlbKkZGoq0PgaHkeVYKR6rxmAoAsAgGNTPp9Fqj1ropX2idun/kRL80Jz+wrGbQuXfmvj7BTb9YLGqRZUsiddtB6G6mHSeGOT7pYGzp7ekXf4T1brLsSnX2FocrijUlBR/rzwiBZwnJOfcPckUmeu1EksaghdoFRKQjP2FgVgtaU0U29tgBj6uzYQeWc0W1hct/MiDFYqfBK076YpIZwQg3QXzMYSNywtZIr53RZSwPbLYcPkF7O3H3JU="