language: node_js
node_js:
  - node
cache:
  directories:
  - node_modules
dist: trusty
sudo: false
install: 
  - npm ci
before_deploy:
  - npm run build
  - rm -rf node_modules
deploy:
  skip_cleanup: true 
  provider: heroku
  app: swapi-strikes-back
  api_key:
    secure: g+lh2B1HsAHNoqXKzUyhGV/+8AV/YuHS1HygfcOPU1EmeceTNvS4DjqtGmdgnkmZUnzw75jz7O4X0Jr9IDbXYF4NzvROxc0COu5qjOEVItZWk9SFhAwsirlntVYJziWY871baJO2oXK5W9vkYo2z/WyrS11fnjzszLIRIuh9fbZmTb3FPEfaziMd4iCzgGj1xEdeBbdr18jxGLiw7jt1bEdpDyBZsTgXCHzz4AWHe0S34EGXzsekDh1nz1GTChkhEammm/mMdEhQjbmUXD/AKgIjVj3MQ1sN/X/6T80keWgQquQjLM7L7mWAIqrcmqU+7WkPeiU0OW0DV41dzYf6D2o7IKj286on03uoPmoaRmiBSgvKs2vjwHvmeYey/Z7wklcFRYTBsfGveUnvDGZUACVSoqCcZ5XJD3pelzJgtMTZDVFBllnGSCiN5sAA/JbhP5yOMUGBgC+KSvawhi4WABHNaz6I+qSDbEY7phuwGfE+NpJ4PEeJSXyJBSrwk5gi8Q49LHawUfo85VHpuj8sdzc16Z3iPJNAXX6SjY1ruXkHVtalI4/9KNE4MxS2d7QZud4/auVM5wUTy70fCsSd27hH3mX4R5Z8VIKEPIiT/+MSmY81+ZM8ZB2aljkD4cRn5soycuyZrm9j9S3ncZNpgXQmcQSz6sA0iEhnQYHs+Sc=