language: node_js
node_js:
  - node
cache:
  directories:
  - node_modules
dist: trusty
sudo: false
install: 
  - npm ci
before_deploy:
  - npm run build
  - rm -rf node_modules
deploy:
  skip_cleanup: true 
  provider: heroku
  app: star-warsapi
  api_key:
    secure: "N+c7frLydgZm5h36lAOBTjdRZMzRkTvHKhxZH1j0KAk2Tr/JPRIVIgtD1bQexf31alefzqQgw68udWNzOTITiTiI0UlaSSdRiL1WabfqI11LCE3F6pu5EeiqSyCIlRTPnoR/zrYA/uF0aOmlyAMs53+UZXiCVHKIu7aLBndB34y+EGyBCBZ9fiwCDViwx3VRd1WCfEzyAkRuBl0LoNrJ91ll5qZ8meTUWje91RnoRZCUjvy5lVesi0mHsUPSLybRYQM+GyUwBby2E1JoaGCqP1ep6VSreGKvvTO+jH6l9pcZGvoYeo/7R233PmM5Elfr8GkKUZMYfGBVXOjhqLDqEmdRnRP81Hp/VC91Pcd/Uv2lPaP17/I/rPrQXKT/1V5+fLSsedLXnPe/7jdFfv2PsCrh5YQ3zjSTlOHdah9rbzCo88YvRCxq58TaWKrH9zjII/ZKQXPqDGcTqclPLdEHGaI3seeR76FVn9cAYHW/tMK1A9+Y6Na+j2nN/eDCprIG5gnC3imC5/YKodrhBwqK7p5khwWIoYGncm0D3v+9gaozL4g50fyzeB+L4nOkdLqvvU3edt20faVSfPBetNdh2OZilbHAjoc4CIh+ShhyfFul+cvf38vOUNramIrod5a8Lo2Zy6ixzpRcOpCmMapKluKeHttKdfHeMdJvrIWAyY4="